/**
 * Lexicon: the user-facing terminology map for theme packs.
 *
 * Internal domain language (DB tables, types, variables) remains
 * guild/quest/loot/adventurer/NPC permanently — the lexicon translates ONLY
 * user-facing strings. Example: key `quest` renders "Quest" (high-fantasy),
 * "Mission" (sci-fi), "Level" (retro-gaming).
 *
 * HARD RULE: no hardcoded user-facing strings in screens or components — all
 * copy resolves through these keys via the `useLexicon` hook (t(key)).
 *
 * Strings may contain `{placeholders}` filled by t(key, vars).
 * Resolution fallback chain: active variant → active pack → high-fantasy base.
 */

export const lexiconKeys = [
  // Core domain terms
  'guild',
  'npc',
  'adventurer',
  'quest',
  'quest_plural',
  'complete_action',
  'gold',
  'xp',
  'level',
  'loot',
  'loot_list',
  'streak',
  'store',
  'achievement_points',
  // Moments
  'level_up_title',
  'level_up_body',
  'pairing_title',
  'greeting_morning',
  'greeting_afternoon',
  'greeting_evening',
  // Dashboard / quest log
  'rank_title',
  'xp_to_next',
  'xp_earned',
  'quests_today_label',
  'daily_progress_label',
  'today_label',
  'done_label',
  'all_done_title',
  'all_done_body',
  'empty_quests_body',
  // Store / loot
  'store_subtitle',
  'empty_loot_title',
  'empty_loot_body',
  'requested_label',
  'owned_label',
  'stock_left',
  'xp_unlocks_title',
  'xp_unlocks_body',
  'filter_all',
  'filter_experiences',
  'filter_stuff',
  'filter_special',
  // Profile
  'badge_collection_title',
  'quests_done_label',
  'badges_label',
  'preview_level_up',
  // --- NPC-side keys below: defined in the base lexicon only (NPC mode uses
  // --- the neutral skin + base terms; packs fall back via the chain).
  // Auth
  'auth_signup_title',
  'auth_signup_subtitle',
  'auth_signin_title',
  'auth_signin_subtitle',
  'auth_email_label',
  'auth_password_label',
  'auth_confirm_password_label',
  'auth_create_account_action',
  'auth_sign_in_action',
  'auth_have_account',
  'auth_need_account',
  'auth_consent_label',
  'auth_consent_required',
  'auth_invalid_email',
  'auth_password_min',
  'auth_passwords_match',
  'auth_confirm_email_title',
  'auth_confirm_email_body',
  'auth_callback_verifying',
  'auth_callback_failed',
  // Walkthrough
  'walkthrough_skip',
  'walkthrough_next',
  'walkthrough_done',
  'walkthrough_step1_title',
  'walkthrough_step1_body',
  'walkthrough_step2_title',
  'walkthrough_step2_body',
  'walkthrough_step3_title',
  'walkthrough_step3_body',
  'walkthrough_notify_title',
  'walkthrough_notify_body',
  'walkthrough_notify_note',
  // Guild creation
  'guild_create_title',
  'guild_create_subtitle',
  'guild_name_label',
  'guild_name_placeholder',
  'guild_crest_label',
  'guild_create_action',
  // Adventurer management
  'adventurers_empty_title',
  'adventurers_empty_body',
  'adventurer_add_action',
  'adventurer_new_title',
  'adventurer_edit_title',
  'adventurer_nickname_label',
  'adventurer_nickname_required',
  'adventurer_age_label',
  'adventurer_theme_label',
  'adventurer_variant_label',
  'variant_default_label',
  'adventurer_save_action',
  'adventurer_archive_action',
  'adventurer_restore_action',
  'archived_section_label',
  'premium_lock_label',
  // Limits / paywall
  'limit_title',
  'limit_body',
  'upgrade_action',
  'not_now_action',
  'paywall_title',
  'paywall_subtitle',
  'paywall_benefit_npcs',
  'paywall_benefit_adventurers',
  'paywall_benefit_quests',
  'paywall_benefit_themes',
  'paywall_price_line',
  // Device pairing (NPC side)
  'pair_device_action',
  'pairing_code_hint',
  'pairing_code_expires_in',
  'pairing_code_expired',
  'regenerate_code_action',
  'devices_section_label',
  'no_devices_label',
  'device_default_label',
  'device_revoke_action',
  'device_revoked_label',
  'device_last_seen',
  // Device pairing (kid side)
  'pair_enter_code_hint',
  'pair_submit_action',
  'pair_error_wrong_code',
  'pair_error_expired',
  'pair_error_used',
  'pair_error_generic',
  'pair_revoked_title',
  'pair_revoked_body',
  'pair_again_action',
  'pair_welcome_link',
  // Mode toggle
  'mode_enter_adventurer_action',
  'mode_back_to_npc_action',
  'mode_choose_adventurer_title',
  'mode_no_adventurers_body',
  'mode_pin_title',
  'mode_pin_body',
  'mode_pin_set_title',
  'mode_pin_set_body',
  'mode_pin_label',
  'mode_pin_save_action',
  'mode_pin_error',
  // NPC dashboard / tabs
  'tab_home',
  'home_roster_label',
  'loot_coming_title',
  'loot_coming_body',
  'preset_library_label',
  'recurrence_daily',
  'recurrence_weekly',
  'recurrence_monthly',
  'recurrence_once',
  // Quest categories (themed labels; ids stay chores/hygiene/school/kindness/exercise)
  'category_chores',
  'category_hygiene',
  'category_school',
  'category_kindness',
  'category_exercise',
  // Preset quest flavor text (titles stay literal; flavor varies per theme)
  'preset_flavor_make_bed',
  'preset_flavor_tidy_room',
  'preset_flavor_set_table',
  'preset_flavor_unload_dishwasher',
  'preset_flavor_take_out_trash',
  'preset_flavor_feed_pet',
  'preset_flavor_brush_teeth',
  'preset_flavor_take_shower',
  'preset_flavor_brush_hair',
  'preset_flavor_clothes_in_hamper',
  'preset_flavor_wash_hands',
  'preset_flavor_trim_nails',
  'preset_flavor_homework',
  'preset_flavor_read_20',
  'preset_flavor_pack_bag',
  'preset_flavor_practice_instrument',
  'preset_flavor_study_spelling',
  'preset_flavor_organize_desk',
  'preset_flavor_help_sibling',
  'preset_flavor_write_thanks',
  'preset_flavor_give_compliment',
  'preset_flavor_share_toy',
  'preset_flavor_call_grandparent',
  'preset_flavor_carry_groceries',
  'preset_flavor_walk_dog',
  'preset_flavor_bike_ride',
  'preset_flavor_play_outside',
  'preset_flavor_stretch',
  'preset_flavor_sports_practice',
  'preset_flavor_dance_party',
  // Quest log (NPC)
  'quest_log_view_today',
  'quest_log_view_week',
  'quest_log_view_month',
  'quest_log_view_by_adventurer',
  'quest_status_pending',
  'quest_status_in_progress',
  'quest_status_completed',
  'quest_status_expired',
  'quest_new_action',
  'browse_presets_action',
  'quest_log_empty',
  'quest_unassigned_label',
  'quest_required_badge',
  // Quest builder form
  'quest_new_title',
  'quest_edit_title',
  'quest_title_label',
  'quest_title_required',
  'quest_description_label',
  'quest_category_label',
  'quest_gold_label',
  'quest_xp_label',
  'quest_reward_invalid',
  'quest_required_label',
  'quest_required_hint',
  'quest_approval_label',
  'quest_approval_hint',
  'quest_assign_label',
  'quest_assign_required',
  'quest_recurrence_label',
  'recurrence_monthly_day_label',
  'recurrence_weekly_days_required',
  'recurrence_once_date_label',
  'recurrence_date_invalid',
  'time_window_label',
  'time_window_start_label',
  'time_window_end_label',
  'time_window_invalid',
  'quest_save_action',
  'quest_archive_action',
  'quest_restore_action',
  'quest_delete_action',
  'quest_delete_confirm_body',
  'quest_limit_title',
  'quest_limit_body',
  'preset_use_action',
  // Completion flow (kid-visible)
  'quest_awaiting_approval',
  'quest_rejected_kind',
  'quest_try_again_action',
  'complete_error_body',
  'streak_bonus_label',
  // Level-up celebration (kid-visible)
  'level_up_spoils_label',
  'level_up_points_line',
  'level_up_continue_action',
  // Approval queue (NPC)
  'approvals_title',
  'approvals_link_label',
  'approvals_empty_body',
  'approve_action',
  'reject_action',
  'reject_modal_title',
  'reject_reason_label',
  'reject_reason_required',
  'completed_when_label',
  // Welcome / settings / errors
  'welcome_intro_label',
  'welcome_tagline',
  'welcome_cta',
  'settings_title',
  'settings_subtitle',
  'settings_session_label',
  'sign_out_action',
  'settings_reset_title',
  'settings_reset_body',
  'settings_reset_action',
  'settings_reset_confirm_body',
  'cancel_action',
  'error_boundary_title',
  'error_boundary_body',
  // Adventurer profile & avatar (kid-visible)
  'profile_title',
  'equipped_section_label',
  'avatar_base_label',
  'empty_slot_label',
  // Cosmetic store (kid-visible)
  'cosmetic_store_title',
  'cosmetic_store_subtitle',
  'slot_head',
  'slot_body',
  'slot_accessory',
  'unlock_action',
  'equip_action',
  'unequip_action',
  'equipped_label',
  'cosmetic_cost_label',
  'cosmetic_need_more',
  'cosmetic_premium_locked_label',
  'cosmetic_premium_nudge',
  // Cosmetic item names — themed per pack, joined on cosmetic_items.item_key
  'cosmetic_head_starter_name',
  'cosmetic_head_guard_name',
  'cosmetic_head_crown_name',
  'cosmetic_head_mythic_name',
  'cosmetic_body_starter_name',
  'cosmetic_body_scout_name',
  'cosmetic_body_knight_name',
  'cosmetic_body_mythic_name',
  'cosmetic_acc_starter_name',
  'cosmetic_acc_charm_name',
  'cosmetic_acc_banner_name',
  'cosmetic_acc_mythic_name',
  // Achievements (kid-visible)
  'achievement_earned_title',
  'achievements_title',
  'achievements_progress',
  'achievement_locked_label',
  'ach_first_quest_name',
  'ach_first_quest_desc',
  'ach_quests_10_name',
  'ach_quests_10_desc',
  'ach_quests_25_name',
  'ach_quests_25_desc',
  'ach_quests_50_name',
  'ach_quests_50_desc',
  'ach_quests_100_name',
  'ach_quests_100_desc',
  'ach_quests_250_name',
  'ach_quests_250_desc',
  'ach_streak_3_name',
  'ach_streak_3_desc',
  'ach_streak_7_name',
  'ach_streak_7_desc',
  'ach_streak_14_name',
  'ach_streak_14_desc',
  'ach_streak_30_name',
  'ach_streak_30_desc',
  'ach_level_5_name',
  'ach_level_5_desc',
  'ach_level_10_name',
  'ach_level_10_desc',
  'ach_level_25_name',
  'ach_level_25_desc',
  'ach_level_50_name',
  'ach_level_50_desc',
  'ach_first_redemption_name',
  'ach_first_redemption_desc',
  'ach_redemptions_10_name',
  'ach_redemptions_10_desc',
  'ach_required_week_name',
  'ach_required_week_desc',
  // --- Loot economy (real-world rewards) ---
  // NPC loot library (feature 19)
  'loot_manage_title',
  'loot_manage_subtitle',
  'loot_custom_section',
  'loot_presets_section',
  'loot_custom_empty_body',
  'loot_new_action',
  'loot_edit_title',
  'loot_form_name_label',
  'loot_form_name_required',
  'loot_form_description_label',
  'loot_form_cost_label',
  'loot_form_cost_invalid',
  'loot_form_stock_label',
  'loot_form_stock_hint',
  'loot_form_stock_invalid',
  'loot_save_action',
  'loot_delete_action',
  'loot_delete_confirm_body',
  'loot_limit_title',
  'loot_limit_body',
  'loot_unlimited_label',
  'sold_out_label',
  // Redemption — kid shop (feature 20)
  'loot_shop_title',
  'loot_shop_subtitle',
  'redeem_action',
  'redeem_confirm_title',
  'redeem_confirm_body',
  'redeem_confirm_action',
  'redeem_success_body',
  'redeem_sold_out_body',
  'redeem_error_body',
  'insufficient_gold_title',
  'insufficient_gold_quests',
  'insufficient_gold_generic',
  // Redemption history — kid
  'loot_history_title',
  'loot_history_link',
  'redemption_pending_chip',
  'redemption_fulfilled_chip',
  'redemption_denied_chip',
  'redemption_pending_body',
  'redemption_fulfilled_body',
  'redemption_denied_body',
  // Fulfillment — NPC (feature 20)
  'fulfillment_title',
  'fulfillment_link_label',
  'fulfillment_empty_body',
  'fulfill_action',
  'deny_action',
  'redemption_history_section',
  'redemption_spent_label',
  'fulfillment_sold_out_error',
  // Wish list — kid (feature 21)
  'wishlist_title',
  'wishlist_subtitle',
  'wishlist_propose_action',
  'wishlist_empty_title',
  'wishlist_empty_body',
  'wish_form_title',
  'wish_form_name_label',
  'wish_form_name_required',
  'wish_form_why_label',
  'wish_form_cost_label',
  'wish_form_cost_invalid',
  'wish_form_submit_action',
  'wish_status_proposed_chip',
  'wish_status_accepted_chip',
  'wish_status_declined_chip',
  'wish_declined_kind',
  // Wish list review — NPC (feature 21)
  'wishlist_review_title',
  'wishlist_review_link_label',
  'wishlist_review_empty_body',
  'wish_accept_action',
  'wish_decline_action',
  'wish_accept_title',
  'wish_proposed_cost_label',
  'wish_no_cost_label',
  'wish_why_section',
  // Realtime / connectivity
  'offline_indicator',
  // Notification preferences (NPC)
  'settings_notifications_label',
  'notif_master_label',
  'notif_master_hint',
  'notif_quiet_hours_label',
  'notif_quiet_hours_hint',
  'notif_quiet_start_label',
  'notif_quiet_end_label',
  'notif_events_label',
  'notif_event_quest_completed',
  'notif_event_redemption_requested',
  'notif_event_wishlist_proposed',
  'notif_adventurers_label',
  // Co-parent invites (feature 24)
  'invite_coparent_action',
  'invite_premium_required',
  'invite_code_title',
  'invite_code_share_hint',
  'invite_share_action',
  'invite_copy_done',
  'invite_accept_title',
  'invite_accept_subtitle',
  'invite_code_label',
  'invite_accept_action',
  'invite_accept_success',
  'invite_error_not_found',
  'invite_error_expired',
  'invite_error_used',
  'invite_error_already_member',
  'invite_error_limit',
  'invite_error_generic',
  // Paywall — contextual headlines (one per trigger point) + UI (feature 24)
  'paywall_headline_theme_lock',
  'paywall_headline_adventurer_limit',
  'paywall_headline_quest_limit',
  'paywall_headline_loot_limit',
  'paywall_headline_coparent',
  'paywall_headline_history',
  'paywall_headline_default',
  'paywall_theme_sell_title',
  'paywall_locked_theme_label',
  'paywall_limit_grid_title',
  'paywall_grid_col_free',
  'paywall_grid_col_premium',
  'paywall_grid_npcs',
  'paywall_grid_adventurers',
  'paywall_grid_quests',
  'paywall_grid_loot',
  'paywall_grid_history',
  'paywall_grid_cosmetics',
  'paywall_grid_scheduling',
  'paywall_value_unlimited',
  'paywall_monthly_label',
  'paywall_annual_label',
  'paywall_trial_badge',
  'paywall_restore_action',
  'paywall_purchase_error',
  'paywall_unavailable_note',
  'paywall_restored_success',
  'paywall_restored_none',
  // Premium downgrade — read-only locked rows (feature 24 / downgrade matrix)
  'locked_badge_label',
  'locked_upgrade_nudge',
  // Settings & privacy (feature 25)
  'settings_subscription_label',
  'settings_subscription_premium_status',
  'settings_subscription_free_status',
  'settings_manage_subscription_action',
  'settings_upgrade_action',
  'settings_adventurers_label',
  'settings_adventurers_hint',
  'settings_manage_adventurers_action',
  'settings_devices_label',
  'settings_devices_hint',
  'settings_data_label',
  'settings_export_action',
  'settings_export_hint',
  'settings_legal_label',
  'settings_privacy_action',
  'settings_terms_action',
  'settings_delete_guild_label',
  'settings_delete_guild_body',
  'settings_delete_guild_action',
  'settings_delete_confirm_title',
  'settings_delete_confirm_body',
  'settings_delete_confirm_input_label',
  'settings_delete_confirm_action',
  'data_export_title',
  'data_export_subtitle',
  'data_export_copy_action',
  'data_export_copied',
  'data_export_loading',
  'data_export_error',
  // Misc
  'error_generic',
] as const;

export type LexiconKey = (typeof lexiconKeys)[number];

/** A complete lexicon (the high-fantasy base must satisfy this). */
export type Lexicon = Record<LexiconKey, string>;

/** Packs and variants may override any subset; the chain fills the rest. */
export type PartialLexicon = Partial<Lexicon>;

export type LexiconVars = Record<string, string | number>;

const interpolate = (template: string, vars?: LexiconVars): string =>
  vars
    ? template.replace(/\{(\w+)\}/g, (match, name: string) =>
        name in vars ? String(vars[name]) : match,
      )
    : template;

/**
 * Builds a typed t() over the fallback chain: variant → pack → base.
 * The base lexicon is complete, so t() always returns a string.
 */
export const makeTranslator =
  (base: Lexicon, pack?: PartialLexicon, variant?: PartialLexicon) =>
  (key: LexiconKey, vars?: LexiconVars): string =>
    interpolate(variant?.[key] ?? pack?.[key] ?? base[key], vars);
