import iconQuest from '../assets/images/themes/high-fantasy/icon-quest.png';
import iconLoot from '../assets/images/themes/high-fantasy/icon-loot.png';
import iconGold from '../assets/images/themes/high-fantasy/icon-gold.png';
import iconStreak from '../assets/images/themes/high-fantasy/icon-streak.png';
import avatarA from '../assets/images/themes/high-fantasy/avatar-a.png';
import avatarB from '../assets/images/themes/high-fantasy/avatar-b.png';
import avatarC from '../assets/images/themes/high-fantasy/avatar-c.png';
import cosmeticHeadStarter from '../assets/images/themes/high-fantasy/cosmetic-head-starter.png';
import cosmeticHeadGuard from '../assets/images/themes/high-fantasy/cosmetic-head-guard.png';
import cosmeticHeadCrown from '../assets/images/themes/high-fantasy/cosmetic-head-crown.png';
import cosmeticHeadMythic from '../assets/images/themes/high-fantasy/cosmetic-head-mythic.png';
import cosmeticBodyStarter from '../assets/images/themes/high-fantasy/cosmetic-body-starter.png';
import cosmeticBodyScout from '../assets/images/themes/high-fantasy/cosmetic-body-scout.png';
import cosmeticBodyKnight from '../assets/images/themes/high-fantasy/cosmetic-body-knight.png';
import cosmeticBodyMythic from '../assets/images/themes/high-fantasy/cosmetic-body-mythic.png';
import cosmeticAccStarter from '../assets/images/themes/high-fantasy/cosmetic-acc-starter.png';
import cosmeticAccCharm from '../assets/images/themes/high-fantasy/cosmetic-acc-charm.png';
import cosmeticAccBanner from '../assets/images/themes/high-fantasy/cosmetic-acc-banner.png';
import cosmeticAccMythic from '../assets/images/themes/high-fantasy/cosmetic-acc-mythic.png';
import soundQuestComplete from '../assets/sounds/themes/high-fantasy/quest-complete.wav';
import soundLevelUp from '../assets/sounds/themes/high-fantasy/level-up.wav';
import soundGoldPickup from '../assets/sounds/themes/high-fantasy/gold-pickup.wav';
import soundLootRedeem from '../assets/sounds/themes/high-fantasy/loot-redeem.wav';

import { highFantasyPalette } from '../constants/theme';
import type { Lexicon } from '../lib/lexicon';
import type { ThemePack } from '../types/theme';

/**
 * The complete base lexicon — the end of every fallback chain. Every key must
 * be present here (enforced by the Lexicon type).
 */
export const baseLexicon: Lexicon = {
  guild: 'Guild',
  npc: 'Guild Master',
  adventurer: 'Adventurer',
  quest: 'Quest',
  quest_plural: 'Quests',
  complete_action: 'Complete Quest',
  gold: 'Gold',
  xp: 'XP',
  level: 'Level',
  loot: 'Loot',
  loot_list: 'Loot List',
  streak: 'Streak',
  store: 'Marketplace',
  achievement_points: 'Glory',
  level_up_title: 'Level Up!',
  level_up_body: 'Your legend grows. Onward, brave adventurer!',
  pairing_title: 'Join your Guild',
  greeting_morning: 'Good morrow',
  greeting_afternoon: 'Good day',
  greeting_evening: 'Good eve',
  rank_title: 'Level {level} Adventurer',
  xp_to_next: '{xp} XP to Level {level}',
  xp_earned: '+{xp} XP earned',
  quests_today_label: "Today's Quests",
  daily_progress_label: 'Daily Progress',
  today_label: 'today',
  done_label: 'Done!',
  all_done_title: 'All Clear!',
  all_done_body: 'Every quest conquered. The Guild is proud of you.',
  empty_quests_body: 'No quests on the board today. Rest well, adventurer.',
  store_subtitle: 'Spend your hard-earned gold',
  empty_loot_title: 'The shelves are bare',
  empty_loot_body: 'Ask your Guild Master to stock the marketplace.',
  requested_label: 'Requested',
  owned_label: 'Owned',
  stock_left: '{count} left',
  xp_unlocks_title: 'XP Unlocks',
  xp_unlocks_body: 'Avatar treasures — earn XP, keep them forever',
  filter_all: 'All',
  filter_experiences: 'Adventures',
  filter_stuff: 'Treasures',
  filter_special: 'Special',
  badge_collection_title: 'Badge Collection',
  quests_done_label: 'Quests Done',
  badges_label: 'Badges',
  preview_level_up: 'Preview the level up ceremony',
  // NPC-side copy (neutral skin) — theme-neutral, clear and adult.
  auth_signup_title: 'Create your account',
  auth_signup_subtitle: 'One account for parents. Set up your family in a few guided steps.',
  auth_signin_title: 'Welcome back',
  auth_signin_subtitle: 'Sign in to manage quests, rewards, and your adventurers.',
  auth_email_label: 'Email',
  auth_password_label: 'Password',
  auth_confirm_password_label: 'Confirm password',
  auth_create_account_action: 'Create account',
  auth_sign_in_action: 'Sign in',
  auth_have_account: 'Already have an account?',
  auth_need_account: 'New to Lootlyfe?',
  auth_consent_label:
    'I am the parent or legal guardian of the children who will use this app, and I consent to their participation.',
  auth_consent_required: 'Parental consent is required to create an account.',
  auth_invalid_email: 'Enter a valid email address.',
  auth_password_min: 'Password must be at least 8 characters.',
  auth_passwords_match: 'Passwords must match.',
  auth_confirm_email_title: 'Confirm your email',
  auth_confirm_email_body:
    'We sent you a confirmation link. Open it, then return here and sign in.',
  auth_callback_verifying: 'Confirming your email…',
  auth_callback_failed:
    'That link is invalid or has expired. Sign in to request a fresh one, or just sign in if your email is already confirmed.',
  walkthrough_skip: 'Skip',
  walkthrough_next: 'Next',
  walkthrough_done: 'Get started',
  walkthrough_step1_title: 'Your family is a team',
  walkthrough_step1_body:
    'Lootlyfe turns chores into a game your whole family plays together. Parents run the show; kids join the adventure.',
  walkthrough_step2_title: 'Chores become quests',
  walkthrough_step2_body:
    'Create tasks, set rewards, and watch them get done. Completed quests earn gold and experience points.',
  walkthrough_step3_title: 'Effort earns real rewards',
  walkthrough_step3_body:
    'Kids spend their gold on rewards you define — screen time, outings, treats. You approve every redemption.',
  walkthrough_notify_title: 'Stay in the loop',
  walkthrough_notify_body:
    'Get a heads-up when a quest is finished or a reward is requested, so nothing waits on you.',
  walkthrough_notify_note: "We'll ask for notification permission later, when it matters.",
  guild_create_title: 'Name your guild',
  guild_create_subtitle: 'Your guild is your family’s home base. Pick a name and a crest.',
  guild_name_label: 'Guild name',
  guild_name_placeholder: 'The Rivera Guild',
  guild_crest_label: 'Crest',
  guild_create_action: 'Create guild',
  adventurers_empty_title: 'No adventurers yet',
  adventurers_empty_body: 'Add your first adventurer to start handing out quests.',
  adventurer_add_action: 'Add adventurer',
  adventurer_new_title: 'New adventurer',
  adventurer_edit_title: 'Edit adventurer',
  adventurer_nickname_label: 'Nickname',
  adventurer_nickname_required: 'A nickname is required.',
  adventurer_age_label: 'Age range',
  adventurer_theme_label: 'Theme',
  adventurer_variant_label: 'Style',
  variant_default_label: 'Classic',
  adventurer_save_action: 'Save',
  adventurer_archive_action: 'Archive',
  adventurer_restore_action: 'Restore',
  archived_section_label: 'Archived',
  premium_lock_label: 'Premium',
  limit_title: 'Guild is full',
  limit_body:
    'Free guilds can have up to {limit} adventurers. Upgrade to add more heroes to your roster.',
  upgrade_action: 'See premium',
  not_now_action: 'Not now',
  paywall_title: 'Legendary Guild',
  paywall_subtitle: 'Everything in free, plus room for the whole family.',
  paywall_benefit_npcs: 'Up to 4 parent accounts with co-parent invites',
  paywall_benefit_adventurers: 'Unlimited adventurers',
  paywall_benefit_quests: 'Unlimited custom quests and rewards',
  paywall_benefit_themes: 'All theme packs and seasonal drops',
  paywall_price_line: '$6.99/month or $49.99/year — 7-day free trial',
  pair_device_action: 'Pair a device',
  pairing_code_hint: 'On the kid device, open Lootlyfe and tap "Join with a code", then enter:',
  pairing_code_expires_in: 'Expires in {time}',
  pairing_code_expired: 'This code expired.',
  regenerate_code_action: 'Make a new code',
  devices_section_label: 'Paired devices',
  no_devices_label: 'No devices paired yet.',
  device_default_label: 'Adventurer device',
  device_revoke_action: 'Unpair',
  device_revoked_label: 'Unpaired',
  device_last_seen: 'Last seen {time}',
  pair_enter_code_hint: 'Ask your grown-up for the 6-digit code, then type it here.',
  pair_submit_action: 'Join!',
  pair_error_wrong_code: "Hmm, that code didn't work. Check the numbers and try again!",
  pair_error_expired: 'That code took a little nap and expired. Ask for a fresh one!',
  pair_error_used: 'That code was already used. Ask your grown-up for a new one!',
  pair_error_generic: "Something hiccuped. Let's try that again!",
  pair_revoked_title: 'This device took a break',
  pair_revoked_body:
    'Your grown-up unpaired this device. No worries — ask them for a new code to jump back in!',
  pair_again_action: 'Enter a new code',
  pair_welcome_link: 'Join with a code',
  mode_enter_adventurer_action: 'Adventurer mode',
  mode_back_to_npc_action: 'Parent mode',
  mode_choose_adventurer_title: 'Who is playing?',
  mode_no_adventurers_body: 'Add an adventurer from the Family tab first.',
  mode_pin_title: 'Enter your PIN',
  mode_pin_body: 'Enter your 4-digit PIN to switch back to parent mode.',
  mode_pin_set_title: 'Set a parent PIN',
  mode_pin_set_body:
    'This 4-digit PIN keeps kids from switching back to parent mode. You can change it later in settings.',
  mode_pin_label: 'PIN',
  mode_pin_save_action: 'Save PIN',
  mode_pin_error: "That PIN doesn't match. Try again.",
  tab_home: 'Home',
  home_roster_label: 'Your adventurers',
  loot_coming_title: 'Loot forge coming soon',
  loot_coming_body:
    'Browse the preset rewards below — stocking your own treasury lands in the next update.',
  preset_library_label: 'Preset library',
  recurrence_daily: 'Daily',
  recurrence_weekly: 'Weekly',
  recurrence_monthly: 'Monthly',
  recurrence_once: 'One-time',
  // Quest categories — themed labels over stable ids.
  category_chores: 'Castle Chores',
  category_hygiene: 'Clean & Gleam',
  category_school: 'Scholar Training',
  category_kindness: 'Deeds of Honor',
  category_exercise: 'Strength Training',
  // Preset flavor text. Titles stay literal; this copy is the themed part.
  preset_flavor_make_bed: 'Smooth the blankets and fluff the pillows — a knight keeps a tidy bunk.',
  preset_flavor_tidy_room: 'Toys in chests, clothes in the hamper, floor visible.',
  preset_flavor_set_table: 'Plates, cups, and cutlery for the whole party.',
  preset_flavor_unload_dishwasher: 'Put away the clean dishes, safe and sound.',
  preset_flavor_take_out_trash: 'Kitchen trash and recycling out to the outer bins.',
  preset_flavor_feed_pet: 'Measure the food and refresh the water for your loyal companion.',
  preset_flavor_brush_teeth: 'Two full minutes, morning and night.',
  preset_flavor_take_shower: 'Soap, scrub, rinse — emerge gleaming.',
  preset_flavor_brush_hair: 'Tame the wild mane before you head out.',
  preset_flavor_clothes_in_hamper: 'Dirty garb goes in the hamper, not on the floor.',
  preset_flavor_wash_hands: 'Soap and water before the feast.',
  preset_flavor_trim_nails: 'Neat claws for a tidy adventurer.',
  preset_flavor_homework: 'All of it, before screens.',
  preset_flavor_read_20: 'Any book counts. Comics too.',
  preset_flavor_pack_bag: 'Homework, water bottle, and lunch — all aboard.',
  preset_flavor_practice_instrument: '15 minutes of bardic training.',
  preset_flavor_study_spelling: "Master this week's words like ancient runes.",
  preset_flavor_organize_desk: 'A clear desk makes a sharp mind.',
  preset_flavor_help_sibling: 'Teamwork makes the dream work.',
  preset_flavor_write_thanks: 'To a friend, teacher, or family member.',
  preset_flavor_give_compliment: 'Mean it. Watch them light up.',
  preset_flavor_share_toy: "Generosity is a hero's trait.",
  preset_flavor_call_grandparent: 'Share your latest adventures with an elder.',
  preset_flavor_carry_groceries: 'Haul the supplies in from the wagon.',
  preset_flavor_walk_dog: 'A proper patrol around the block.',
  preset_flavor_bike_ride: 'Ride your trusty steed around the neighborhood.',
  preset_flavor_play_outside: 'Fresh air and adventure await beyond the gates.',
  preset_flavor_stretch: 'Limber up like a rogue before a heist.',
  preset_flavor_sports_practice: 'Train hard with your fellow squires.',
  preset_flavor_dance_party: "Crank the bard's tunes and move.",
  // Quest log (NPC neutral skin — clear and adult).
  quest_log_view_today: 'Today',
  quest_log_view_week: 'Week',
  quest_log_view_month: 'Month',
  quest_log_view_by_adventurer: 'By adventurer',
  quest_status_pending: 'Pending',
  quest_status_in_progress: 'In progress',
  quest_status_completed: 'Done',
  quest_status_expired: 'Expired',
  quest_new_action: 'New quest',
  browse_presets_action: 'Browse presets',
  quest_log_empty: 'Nothing scheduled here yet.',
  quest_unassigned_label: 'Unassigned',
  quest_required_badge: 'Required',
  // Quest builder form.
  quest_new_title: 'New quest',
  quest_edit_title: 'Edit quest',
  quest_title_label: 'Title',
  quest_title_required: 'A title is required.',
  quest_description_label: 'Description',
  quest_category_label: 'Category',
  quest_gold_label: 'Gold reward',
  quest_xp_label: 'XP reward',
  quest_reward_invalid: 'Enter a number of 0 or more.',
  quest_required_label: 'Required quest',
  quest_required_hint: 'A must-do, not an extra.',
  quest_approval_label: 'Requires approval',
  quest_approval_hint: 'You confirm completion before rewards pay out.',
  quest_assign_label: 'Assign to',
  quest_assign_required: 'Pick at least one adventurer.',
  quest_recurrence_label: 'Repeats',
  recurrence_monthly_day_label: 'Day of month',
  recurrence_weekly_days_required: 'Pick at least one day.',
  recurrence_once_date_label: 'Date',
  recurrence_date_invalid: 'Use YYYY-MM-DD.',
  time_window_label: 'Time window',
  time_window_start_label: 'From',
  time_window_end_label: 'Until',
  time_window_invalid: 'Use HH:MM, with start before end.',
  quest_save_action: 'Save quest',
  quest_archive_action: 'Archive',
  quest_restore_action: 'Restore',
  quest_delete_action: 'Delete',
  quest_delete_confirm_body: 'This permanently removes the quest and its completion history.',
  quest_limit_title: 'Quest board is full',
  quest_limit_body:
    'Free guilds can have up to {limit} active custom quests. Upgrade for unlimited quests, or archive an old one.',
  preset_use_action: 'Use',
  welcome_intro_label: 'Welcome to',
  welcome_tagline: 'Turn everyday chores into epic quests. Earn loot. Level up. Become legendary.',
  welcome_cta: 'Start your quest →',
  settings_title: 'App & account',
  settings_subtitle:
    'Local data and session. Manage your guild and adventurers from the Guild tab.',
  settings_session_label: 'Session',
  sign_out_action: 'Sign out',
  settings_reset_title: 'Start fresh on this device',
  settings_reset_body:
    'Clears saved preferences and signs you out. Your account and guild data stay safe online.',
  settings_reset_action: 'Reset app & sign out',
  settings_reset_confirm_body:
    'This signs you out and clears cached data on this device. Your account still exists.',
  cancel_action: 'Cancel',
  error_boundary_title: 'Something went wrong',
  error_boundary_body: 'Please restart the app and try again.',
  error_generic: 'Something went wrong. Please try again.',
  // Realtime / connectivity.
  offline_indicator: 'Offline — reconnecting…',
  // Notification preferences (NPC).
  settings_notifications_label: 'Notifications',
  notif_master_label: 'Push notifications',
  notif_master_hint: 'Quest approvals, reward requests, and milestones.',
  notif_quiet_hours_label: 'Quiet hours',
  notif_quiet_hours_hint: "We won't notify you during this window.",
  notif_quiet_start_label: 'From',
  notif_quiet_end_label: 'To',
  notif_events_label: 'Notify me about',
  notif_event_quest_completed: 'Quests awaiting approval',
  notif_event_redemption_requested: 'Reward requests',
  notif_event_wishlist_proposed: 'Wishlist proposals',
  notif_adventurers_label: 'Per adventurer',
  // Co-parent invites.
  invite_coparent_action: 'Invite a co-parent',
  invite_premium_required: 'Co-parent invites are a Legendary Guild perk. Upgrade to add up to 4 parents.',
  invite_code_title: 'Co-parent invite',
  invite_code_share_hint: 'Share this code — it works for 7 days:',
  invite_share_action: 'Share invite',
  invite_copy_done: 'Copied!',
  invite_accept_title: 'Join a guild',
  invite_accept_subtitle: 'Enter the 8-character invite code a co-parent shared with you.',
  invite_code_label: 'Invite code',
  invite_accept_action: 'Join guild',
  invite_accept_success: "You're in! Welcome to the guild.",
  invite_error_not_found: "That code isn't valid. Double-check it and try again.",
  invite_error_expired: 'That invite has expired. Ask for a fresh code.',
  invite_error_used: 'That invite was already used.',
  invite_error_already_member: "You're already part of this guild.",
  invite_error_limit: 'This guild is full (4 parents max).',
  invite_error_generic: "That didn't work. Please try again.",
  // Paywall — contextual headlines + UI (feature 24)
  paywall_headline_theme_lock: 'Unlock every realm',
  paywall_headline_adventurer_limit: 'Room for the whole party',
  paywall_headline_quest_limit: 'Quests without limits',
  paywall_headline_loot_limit: 'A bigger treasure hoard',
  paywall_headline_coparent: 'Rule the guild together',
  paywall_headline_history: 'See the full saga',
  paywall_headline_default: 'Go Legendary',
  paywall_theme_sell_title: 'New realms to explore',
  paywall_locked_theme_label: 'Locked',
  paywall_limit_grid_title: "What's included",
  paywall_grid_col_free: 'Apprentice',
  paywall_grid_col_premium: 'Legendary',
  paywall_grid_npcs: 'Parent accounts',
  paywall_grid_adventurers: 'Adventurers',
  paywall_grid_quests: 'Custom quests',
  paywall_grid_loot: 'Custom loot',
  paywall_grid_history: 'Quest history',
  paywall_grid_cosmetics: 'Cosmetic store',
  paywall_grid_scheduling: 'Advanced scheduling',
  paywall_value_unlimited: 'Unlimited',
  paywall_monthly_label: 'Monthly',
  paywall_annual_label: 'Annual',
  paywall_trial_badge: '7-day free trial',
  paywall_restore_action: 'Restore purchases',
  paywall_purchase_error: "That purchase didn't go through. Please try again.",
  paywall_unavailable_note: 'Purchases are unavailable in this build.',
  paywall_restored_success: 'Your Legendary Guild is back!',
  paywall_restored_none: 'No previous purchase found on this account.',
  // Premium downgrade — read-only locked rows
  locked_badge_label: 'Locked',
  locked_upgrade_nudge: 'Upgrade to Legendary to unlock this again.',
  // Settings & privacy (feature 25)
  settings_subscription_label: 'Subscription',
  settings_subscription_premium_status: 'Legendary Guild — active',
  settings_subscription_free_status: 'Apprentice Guild — free',
  settings_manage_subscription_action: 'Manage subscription',
  settings_upgrade_action: 'Go Legendary',
  settings_adventurers_label: 'Adventurers',
  settings_adventurers_hint: 'Edit nicknames, themes, or archive a hero.',
  settings_manage_adventurers_action: 'Manage adventurers',
  settings_devices_label: 'Paired devices',
  settings_devices_hint: 'Kid devices linked to your guild. Revoke any you no longer trust.',
  settings_data_label: 'Your data',
  settings_export_action: 'Export guild data',
  settings_export_hint: 'Download a copy of everything in your guild (JSON).',
  settings_legal_label: 'Legal',
  settings_privacy_action: 'Privacy policy',
  settings_terms_action: 'Terms of service',
  settings_delete_guild_label: 'Delete guild',
  settings_delete_guild_body:
    'Permanently deletes your guild and all of its data. This cannot be undone.',
  settings_delete_guild_action: 'Delete guild',
  settings_delete_confirm_title: 'Delete this guild?',
  settings_delete_confirm_body:
    'This erases every adventurer, quest, reward, and progress record. Type the guild name to confirm.',
  settings_delete_confirm_input_label: 'Type "{name}" to confirm',
  settings_delete_confirm_action: 'Delete forever',
  data_export_title: 'Guild data export',
  data_export_subtitle: 'A full copy of your guild data. Copy it anywhere you like.',
  data_export_copy_action: 'Copy to clipboard',
  data_export_copied: 'Copied!',
  data_export_loading: 'Gathering your guild data…',
  data_export_error: "We couldn't build your export. Please try again.",
  // Completion flow (kid-visible; encouraging, never shaming).
  quest_awaiting_approval: 'Sent to your Guild Master — rewards arrive with their blessing!',
  quest_rejected_kind: 'Not counted this time: {reason}. Dust off and try again — you’ve got this!',
  quest_try_again_action: 'Try again',
  complete_error_body: 'That didn’t save — give it another tap!',
  streak_bonus_label: '×{multiplier} streak bonus',
  // Level-up celebration.
  level_up_spoils_label: 'Spoils of victory',
  level_up_points_line: '+{points} Glory',
  level_up_continue_action: 'Onward!',
  // Approval queue (NPC neutral skin).
  approvals_title: 'Approvals',
  approvals_link_label: '{count} waiting for review',
  approvals_empty_body: 'All caught up — nothing waiting for review.',
  approve_action: 'Approve',
  reject_action: 'Send back',
  reject_modal_title: 'Send back this quest?',
  reject_reason_label: 'Why? (shown kindly to your adventurer)',
  reject_reason_required: 'A short reason is required.',
  completed_when_label: 'Completed {when}',
  // Adventurer profile & avatar.
  profile_title: 'Hero Profile',
  equipped_section_label: 'Equipped Gear',
  avatar_base_label: 'Choose your hero',
  empty_slot_label: 'Nothing equipped',
  // Cosmetic store.
  cosmetic_store_title: 'The Outfitter',
  cosmetic_store_subtitle: 'Spend your Glory on legendary looks',
  slot_head: 'Helm',
  slot_body: 'Armor',
  slot_accessory: 'Trinket',
  unlock_action: 'Unlock',
  equip_action: 'Equip',
  unequip_action: 'Unequip',
  equipped_label: 'Equipped',
  cosmetic_cost_label: '{points} Glory',
  cosmetic_need_more: 'Earn {points} more Glory to unlock this!',
  cosmetic_premium_locked_label: 'Legendary Guild',
  cosmetic_premium_nudge:
    'This treasure is for Legendary Guilds. Ask your Guild Master about upgrading!',
  // Cosmetic item names.
  cosmetic_head_starter_name: "Traveler's Hood",
  cosmetic_head_guard_name: 'Guardian Helm',
  cosmetic_head_crown_name: 'Royal Crown',
  cosmetic_head_mythic_name: 'Halo of Legends',
  cosmetic_body_starter_name: "Wanderer's Tunic",
  cosmetic_body_scout_name: "Scout's Vest",
  cosmetic_body_knight_name: "Knight's Plate",
  cosmetic_body_mythic_name: 'Cloak of Legends',
  cosmetic_acc_starter_name: 'Lucky Pin',
  cosmetic_acc_charm_name: 'Crystal Charm',
  cosmetic_acc_banner_name: 'Guild Banner',
  cosmetic_acc_mythic_name: 'Star of Legends',
  // Achievements.
  achievement_earned_title: 'Achievement Unlocked!',
  achievements_title: 'Achievements',
  achievements_progress: '{earned} of {total} earned',
  achievement_locked_label: '???',
  ach_first_quest_name: 'First Steps',
  ach_first_quest_desc: 'Complete your very first quest.',
  ach_quests_10_name: 'Apprentice Adventurer',
  ach_quests_10_desc: 'Complete 10 quests.',
  ach_quests_25_name: 'Seasoned Quester',
  ach_quests_25_desc: 'Complete 25 quests.',
  ach_quests_50_name: 'Quest Veteran',
  ach_quests_50_desc: 'Complete 50 quests.',
  ach_quests_100_name: 'Hundred-Quest Hero',
  ach_quests_100_desc: 'Complete 100 quests.',
  ach_quests_250_name: 'Legend of the Guild',
  ach_quests_250_desc: 'Complete 250 quests.',
  ach_streak_3_name: 'Kindling',
  ach_streak_3_desc: 'Keep a 3-day streak alive.',
  ach_streak_7_name: 'Week of Fire',
  ach_streak_7_desc: 'Keep a 7-day streak alive.',
  ach_streak_14_name: 'Unstoppable',
  ach_streak_14_desc: 'Keep a 14-day streak alive.',
  ach_streak_30_name: 'Eternal Flame',
  ach_streak_30_desc: 'Keep a 30-day streak alive.',
  ach_level_5_name: 'Rising Hero',
  ach_level_5_desc: 'Reach level 5.',
  ach_level_10_name: 'Proven Hero',
  ach_level_10_desc: 'Reach level 10.',
  ach_level_25_name: 'Mythic Hero',
  ach_level_25_desc: 'Reach level 25.',
  ach_level_50_name: 'Living Legend',
  ach_level_50_desc: 'Reach level 50 — the very top.',
  ach_first_redemption_name: 'First Treasure',
  ach_first_redemption_desc: 'Redeem your first loot reward.',
  ach_redemptions_10_name: 'Treasure Hunter',
  ach_redemptions_10_desc: 'Redeem 10 loot rewards.',
  ach_required_week_name: 'Perfect Week',
  ach_required_week_desc: 'Finish every required quest for a whole week.',
  // Loot economy — NPC loot library (neutral skin: clear and adult).
  loot_manage_title: 'Loot',
  loot_manage_subtitle: 'Stock your treasury with real-world rewards kids buy with gold.',
  loot_custom_section: 'Your rewards',
  loot_presets_section: 'Add from presets',
  loot_custom_empty_body: 'No rewards yet. Add your own or start from a preset below.',
  loot_new_action: 'New reward',
  loot_edit_title: 'Edit reward',
  loot_form_name_label: 'Name',
  loot_form_name_required: 'A name is required.',
  loot_form_description_label: 'Description',
  loot_form_cost_label: 'Gold cost',
  loot_form_cost_invalid: 'Enter a number of 0 or more.',
  loot_form_stock_label: 'Stock',
  loot_form_stock_hint: 'Leave blank for unlimited.',
  loot_form_stock_invalid: 'Enter a whole number of 0 or more, or leave blank.',
  loot_save_action: 'Save reward',
  loot_delete_action: 'Delete',
  loot_delete_confirm_body: 'This removes the reward and its redemption history.',
  loot_limit_title: 'Treasury is full',
  loot_limit_body:
    'Free guilds can stock up to {limit} custom rewards. Upgrade for unlimited, or remove one.',
  loot_unlimited_label: 'Unlimited',
  sold_out_label: 'Sold out',
  // Redemption — kid shop.
  loot_shop_title: 'Loot Shop',
  loot_shop_subtitle: 'Spend your gold on real rewards',
  redeem_action: 'Redeem',
  redeem_confirm_title: 'Redeem this loot?',
  redeem_confirm_body: 'Spend {cost} gold on {name}? Your Guild Master will hand it over.',
  redeem_confirm_action: 'Redeem it!',
  redeem_success_body: 'Nice! Your gold is set aside — your Guild Master will deliver soon.',
  redeem_sold_out_body: 'Aw, this one just sold out! Check back later.',
  redeem_error_body: 'That didn’t go through — give it another try!',
  insufficient_gold_title: 'Almost there!',
  insufficient_gold_quests: 'About {count} more quests and this is yours. Keep questing!',
  insufficient_gold_generic: 'Keep questing to earn enough gold for this!',
  // Redemption history — kid.
  loot_history_title: 'My Rewards',
  loot_history_link: 'My rewards',
  redemption_pending_chip: 'Waiting',
  redemption_fulfilled_chip: 'Got it!',
  redemption_denied_chip: 'Refunded',
  redemption_pending_body: 'Waiting for your Guild Master to hand it over.',
  redemption_fulfilled_body: 'Delivered — enjoy your reward!',
  redemption_denied_body: 'This one didn’t go through, so your gold came back.',
  // Fulfillment — NPC.
  fulfillment_title: 'Reward requests',
  fulfillment_link_label: '{count} waiting to fulfill',
  fulfillment_empty_body: 'No reward requests right now.',
  fulfill_action: 'Mark fulfilled',
  deny_action: 'Decline & refund',
  redemption_history_section: 'Past redemptions',
  redemption_spent_label: '{gold} gold',
  fulfillment_sold_out_error: 'That reward is out of stock — decline this request to refund it.',
  // Wish list — kid.
  wishlist_title: 'Loot List',
  wishlist_subtitle: 'Wish for rewards — your Guild Master decides',
  wishlist_propose_action: 'Add a wish',
  wishlist_empty_title: 'Your Loot List is empty',
  wishlist_empty_body: 'Wish for a reward you’d love to see in the shop!',
  wish_form_title: 'Make a wish',
  wish_form_name_label: 'What do you wish for?',
  wish_form_name_required: 'Tell us what you’d like!',
  wish_form_why_label: 'Why I want it (optional)',
  wish_form_cost_label: 'How much gold? (optional)',
  wish_form_cost_invalid: 'Use a whole number, or leave it blank.',
  wish_form_submit_action: 'Send wish',
  wish_status_proposed_chip: 'Waiting',
  wish_status_accepted_chip: 'In the shop!',
  wish_status_declined_chip: 'Maybe later',
  wish_declined_kind: 'Not this time — but keep the ideas coming!',
  // Wish list review — NPC.
  wishlist_review_title: 'Loot List wishes',
  wishlist_review_link_label: '{count} wishes to review',
  wishlist_review_empty_body: 'No new wishes to review.',
  wish_accept_action: 'Add to shop',
  wish_decline_action: 'Not now',
  wish_accept_title: 'Add to the loot shop',
  wish_proposed_cost_label: 'They suggested {cost} gold',
  wish_no_cost_label: 'No price suggested',
  wish_why_section: 'Why they want it',
};

/** Free pack. Its palette doubles as the app-wide token defaults (global.css). */
export const highFantasy: ThemePack = {
  id: 'high-fantasy',
  name: 'High Fantasy',
  premium: false,
  palette: highFantasyPalette,
  typography: {
    headingFont: 'Cinzel',
    accentFont: 'CormorantGaramond',
  },
  lexicon: baseLexicon,
  assets: {
    icons: { quest: iconQuest, loot: iconLoot, gold: iconGold, streak: iconStreak },
    avatarBases: [avatarA, avatarB, avatarC],
    cosmetics: {
      'head-starter': cosmeticHeadStarter,
      'head-guard': cosmeticHeadGuard,
      'head-crown': cosmeticHeadCrown,
      'head-mythic': cosmeticHeadMythic,
      'body-starter': cosmeticBodyStarter,
      'body-scout': cosmeticBodyScout,
      'body-knight': cosmeticBodyKnight,
      'body-mythic': cosmeticBodyMythic,
      'acc-starter': cosmeticAccStarter,
      'acc-charm': cosmeticAccCharm,
      'acc-banner': cosmeticAccBanner,
      'acc-mythic': cosmeticAccMythic,
    },
  },
  sounds: {
    quest_complete: soundQuestComplete,
    level_up: soundLevelUp,
    gold_pickup: soundGoldPickup,
    loot_redeem: soundLootRedeem,
  },
  variants: [
    {
      id: 'ember',
      name: 'Emberforge',
      palette: {
        'accent-progress': '#b35a2e',
        'accent-info': '#8a4f9e',
        'accent-achievement': '#c2452f',
      },
      avatarBases: [0, 2],
    },
    {
      id: 'moonlit',
      name: 'Moonlit Grove',
      palette: {
        'bg-base': '#e8ece5',
        surface: '#f2f5ef',
        'surface-raised': '#fbfcf9',
        border: '#cfdac9',
        'text-primary': '#1f2a26',
        'accent-loot': '#9aa53b',
        'accent-info': '#41818f',
      },
      avatarBases: [1, 2],
    },
  ],
};
