import iconQuest from '../assets/images/themes/high-fantasy/icon-quest.png';
import iconLoot from '../assets/images/themes/high-fantasy/icon-loot.png';
import iconGold from '../assets/images/themes/high-fantasy/icon-gold.png';
import iconStreak from '../assets/images/themes/high-fantasy/icon-streak.png';
import avatarA from '../assets/images/themes/high-fantasy/avatar-a.png';
import avatarB from '../assets/images/themes/high-fantasy/avatar-b.png';
import soundQuestComplete from '../assets/sounds/themes/high-fantasy/quest-complete.wav';
import soundLevelUp from '../assets/sounds/themes/high-fantasy/level-up.wav';
import soundGoldPickup from '../assets/sounds/themes/high-fantasy/gold-pickup.wav';
import soundLootRedeem from '../assets/sounds/themes/high-fantasy/loot-redeem.wav';

import { highFantasyPalette } from '../constants/theme';
import type { Lexicon } from '../lib/lexicon';
import type { ThemePack } from '../types/theme';

/**
 * The complete base lexicon — the end of every fallback chain. Every key must
 * be present here (enforced by the Lexicon type).
 */
export const baseLexicon: Lexicon = {
  guild: 'Guild',
  npc: 'Guild Master',
  adventurer: 'Adventurer',
  quest: 'Quest',
  quest_plural: 'Quests',
  complete_action: 'Complete Quest',
  gold: 'Gold',
  xp: 'XP',
  level: 'Level',
  loot: 'Loot',
  loot_list: 'Loot List',
  streak: 'Streak',
  store: 'Marketplace',
  achievement_points: 'Glory',
  level_up_title: 'Level Up!',
  level_up_body: 'Your legend grows. Onward, brave adventurer!',
  pairing_title: 'Join your Guild',
  greeting_morning: 'Good morrow',
  greeting_afternoon: 'Good day',
  greeting_evening: 'Good eve',
  rank_title: 'Level {level} Adventurer',
  xp_to_next: '{xp} XP to Level {level}',
  xp_earned: '+{xp} XP earned',
  quests_today_label: "Today's Quests",
  daily_progress_label: 'Daily Progress',
  today_label: 'today',
  done_label: 'Done!',
  all_done_title: 'All Clear!',
  all_done_body: 'Every quest conquered. The Guild is proud of you.',
  empty_quests_body: 'No quests on the board today. Rest well, adventurer.',
  store_subtitle: 'Spend your hard-earned gold',
  empty_loot_title: 'The shelves are bare',
  empty_loot_body: 'Ask your Guild Master to stock the marketplace.',
  requested_label: 'Requested',
  owned_label: 'Owned',
  stock_left: '{count} left',
  xp_unlocks_title: 'XP Unlocks',
  xp_unlocks_body: 'Avatar treasures — earn XP, keep them forever',
  filter_all: 'All',
  filter_experiences: 'Adventures',
  filter_stuff: 'Treasures',
  filter_special: 'Special',
  badge_collection_title: 'Badge Collection',
  quests_done_label: 'Quests Done',
  badges_label: 'Badges',
  preview_level_up: 'Preview the level up ceremony',
  // NPC-side copy (neutral skin) — theme-neutral, clear and adult.
  auth_signup_title: 'Create your account',
  auth_signup_subtitle: 'One account for parents. Set up your family in a few guided steps.',
  auth_signin_title: 'Welcome back',
  auth_signin_subtitle: 'Sign in to manage quests, rewards, and your adventurers.',
  auth_email_label: 'Email',
  auth_password_label: 'Password',
  auth_confirm_password_label: 'Confirm password',
  auth_create_account_action: 'Create account',
  auth_sign_in_action: 'Sign in',
  auth_have_account: 'Already have an account?',
  auth_need_account: 'New to Lootlyfe?',
  auth_consent_label:
    'I am the parent or legal guardian of the children who will use this app, and I consent to their participation.',
  auth_consent_required: 'Parental consent is required to create an account.',
  auth_invalid_email: 'Enter a valid email address.',
  auth_password_min: 'Password must be at least 8 characters.',
  auth_passwords_match: 'Passwords must match.',
  auth_confirm_email_title: 'Confirm your email',
  auth_confirm_email_body: 'We sent you a confirmation link. Open it, then return here and sign in.',
  auth_callback_verifying: 'Confirming your email…',
  auth_callback_failed:
    'That link is invalid or has expired. Sign in to request a fresh one, or just sign in if your email is already confirmed.',
  walkthrough_skip: 'Skip',
  walkthrough_next: 'Next',
  walkthrough_done: 'Get started',
  walkthrough_step1_title: 'Your family is a team',
  walkthrough_step1_body:
    'Lootlyfe turns chores into a game your whole family plays together. Parents run the show; kids join the adventure.',
  walkthrough_step2_title: 'Chores become quests',
  walkthrough_step2_body:
    'Create tasks, set rewards, and watch them get done. Completed quests earn gold and experience points.',
  walkthrough_step3_title: 'Effort earns real rewards',
  walkthrough_step3_body:
    'Kids spend their gold on rewards you define — screen time, outings, treats. You approve every redemption.',
  walkthrough_notify_title: 'Stay in the loop',
  walkthrough_notify_body:
    'Get a heads-up when a quest is finished or a reward is requested, so nothing waits on you.',
  walkthrough_notify_note: "We'll ask for notification permission later, when it matters.",
  guild_create_title: 'Name your guild',
  guild_create_subtitle: 'Your guild is your family’s home base. Pick a name and a crest.',
  guild_name_label: 'Guild name',
  guild_name_placeholder: 'The Rivera Guild',
  guild_crest_label: 'Crest',
  guild_create_action: 'Create guild',
  adventurers_empty_title: 'No adventurers yet',
  adventurers_empty_body: 'Add your first adventurer to start handing out quests.',
  adventurer_add_action: 'Add adventurer',
  adventurer_new_title: 'New adventurer',
  adventurer_edit_title: 'Edit adventurer',
  adventurer_nickname_label: 'Nickname',
  adventurer_nickname_required: 'A nickname is required.',
  adventurer_age_label: 'Age range',
  adventurer_theme_label: 'Theme',
  adventurer_variant_label: 'Style',
  variant_default_label: 'Classic',
  adventurer_save_action: 'Save',
  adventurer_archive_action: 'Archive',
  adventurer_restore_action: 'Restore',
  archived_section_label: 'Archived',
  premium_lock_label: 'Premium',
  limit_title: 'Guild is full',
  limit_body:
    'Free guilds can have up to {limit} adventurers. Upgrade to add more heroes to your roster.',
  upgrade_action: 'See premium',
  not_now_action: 'Not now',
  paywall_title: 'Legendary Guild',
  paywall_subtitle: 'Everything in free, plus room for the whole family.',
  paywall_benefit_npcs: 'Up to 4 parent accounts with co-parent invites',
  paywall_benefit_adventurers: 'Unlimited adventurers',
  paywall_benefit_quests: 'Unlimited custom quests and rewards',
  paywall_benefit_themes: 'All theme packs and seasonal drops',
  paywall_price_line: '$6.99/month or $49.99/year — 7-day free trial',
  pair_device_action: 'Pair a device',
  pairing_code_hint: 'On the kid device, open Lootlyfe and tap "Join with a code", then enter:',
  pairing_code_expires_in: 'Expires in {time}',
  pairing_code_expired: 'This code expired.',
  regenerate_code_action: 'Make a new code',
  devices_section_label: 'Paired devices',
  no_devices_label: 'No devices paired yet.',
  device_default_label: 'Adventurer device',
  device_revoke_action: 'Unpair',
  device_revoked_label: 'Unpaired',
  device_last_seen: 'Last seen {time}',
  pair_enter_code_hint: 'Ask your grown-up for the 6-digit code, then type it here.',
  pair_submit_action: 'Join!',
  pair_error_wrong_code: "Hmm, that code didn't work. Check the numbers and try again!",
  pair_error_expired: 'That code took a little nap and expired. Ask for a fresh one!',
  pair_error_used: 'That code was already used. Ask your grown-up for a new one!',
  pair_error_generic: "Something hiccuped. Let's try that again!",
  pair_revoked_title: 'This device took a break',
  pair_revoked_body:
    "Your grown-up unpaired this device. No worries — ask them for a new code to jump back in!",
  pair_again_action: 'Enter a new code',
  pair_welcome_link: 'Join with a code',
  mode_enter_adventurer_action: 'Adventurer mode',
  mode_back_to_npc_action: 'Parent mode',
  mode_choose_adventurer_title: 'Who is playing?',
  mode_no_adventurers_body: 'Add an adventurer from the Family tab first.',
  mode_pin_title: 'Enter your PIN',
  mode_pin_body: 'Enter your 4-digit PIN to switch back to parent mode.',
  mode_pin_set_title: 'Set a parent PIN',
  mode_pin_set_body:
    'This 4-digit PIN keeps kids from switching back to parent mode. You can change it later in settings.',
  mode_pin_label: 'PIN',
  mode_pin_save_action: 'Save PIN',
  mode_pin_error: "That PIN doesn't match. Try again.",
  tab_home: 'Home',
  home_roster_label: 'Your adventurers',
  quests_coming_title: 'Quest builder coming soon',
  quests_coming_body:
    'Browse the preset library below — creating, customizing, and assigning quests lands in the next update.',
  loot_coming_title: 'Loot forge coming soon',
  loot_coming_body:
    'Browse the preset rewards below — stocking your own treasury lands in the next update.',
  preset_library_label: 'Preset library',
  recurrence_daily: 'Daily',
  recurrence_weekly: 'Weekly',
  recurrence_once: 'One-time',
  welcome_intro_label: 'Welcome to',
  welcome_tagline: 'Turn everyday chores into epic quests. Earn loot. Level up. Become legendary.',
  welcome_cta: 'Start your quest →',
  settings_title: 'App & account',
  settings_subtitle: 'Local data and session. Manage your guild and adventurers from the Guild tab.',
  settings_session_label: 'Session',
  sign_out_action: 'Sign out',
  settings_reset_title: 'Start fresh on this device',
  settings_reset_body:
    'Clears saved preferences and signs you out. Your account and guild data stay safe online.',
  settings_reset_action: 'Reset app & sign out',
  settings_reset_confirm_body:
    'This signs you out and clears cached data on this device. Your account still exists.',
  cancel_action: 'Cancel',
  error_boundary_title: 'Something went wrong',
  error_boundary_body: 'Please restart the app and try again.',
  error_generic: 'Something went wrong. Please try again.',
};

/** Free pack. Its palette doubles as the app-wide token defaults (global.css). */
export const highFantasy: ThemePack = {
  id: 'high-fantasy',
  name: 'High Fantasy',
  premium: false,
  palette: highFantasyPalette,
  typography: {
    headingFont: 'Cinzel',
    accentFont: 'CormorantGaramond',
  },
  lexicon: baseLexicon,
  assets: {
    icons: { quest: iconQuest, loot: iconLoot, gold: iconGold, streak: iconStreak },
    avatarBases: [avatarA, avatarB],
  },
  sounds: {
    quest_complete: soundQuestComplete,
    level_up: soundLevelUp,
    gold_pickup: soundGoldPickup,
    loot_redeem: soundLootRedeem,
  },
  variants: [
    {
      id: 'ember',
      name: 'Emberforge',
      palette: {
        'accent-progress': '#b35a2e',
        'accent-info': '#8a4f9e',
        'accent-achievement': '#c2452f',
      },
      avatarBases: [0],
    },
    {
      id: 'moonlit',
      name: 'Moonlit Grove',
      palette: {
        'bg-base': '#e8ece5',
        surface: '#f2f5ef',
        'surface-raised': '#fbfcf9',
        border: '#cfdac9',
        'text-primary': '#1f2a26',
        'accent-loot': '#9aa53b',
        'accent-info': '#41818f',
      },
      avatarBases: [1],
    },
  ],
};
